# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wordless
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: wordless-backend-websocket-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: wordless-backend-websocket-api

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UserConnectionTable, Arn]
            - arn:aws:dynamodb:us-west-2:${aws:accountId}:table/emote-reaction-table-${sls:stage}
            - arn:aws:dynamodb:us-west-2:${aws:accountId}:table/users-table-${sls:stage}
            - arn:aws:dynamodb:us-west-2:${aws:accountId}:table/user-sub-table-${sls:stage}
  environment:
    USER_CONNECTION_TABLE: "user-connection-table-${sls:stage}"
    EMOTE_REACTION_TABLE: "emote-reaction-table-${sls:stage}"
    USERS_TABLE: "users-table-${sls:stage}"
    USER_SUB_TABLE: "user-sub-table-${sls:stage}"
    DEPLOY_ENV: ${sls:stage}
    DB_HOST: ${self:custom.db_host.${sls:stage}}
    DB_USER: ${self:custom.db_user.${sls:stage}}
    DB_PASSWORD: ${self:custom.db_password.${sls:stage}}
    DB_NAME: ${self:custom.db_name.${sls:stage}}
    COGNITO_USER_POOL_ID: ${self:custom.cognito_user_pool_id.${sls:stage}}
    COGNITO_REGION: us-west-2
    WEBSOCKET_ENDPOINT: ${self:custom.websocket_endpoint.${sls:stage}}
  websocketsApiName: wordless-backend-websocket-api-${sls:stage}

functions:
  connectionHandler:
    handler: app/onconnect/handler.connect
    events:
      - websocket:
          route: $connect
  disconnectionHandler:
    handler: app/ondisconnect/handler.disconnect
    events:
      - websocket:
          route: $disconnect
    vpc:
      securityGroupIds: ${self:custom.security-group-id.${sls:stage}}
      subnetIds: ${self:custom.vpc_subnet_id.${sls:stage}}
  reactionHandler:
    handler: app/onReact/handler.onReact
    events:
      - websocket:
          route: onReact
  postEmoteHandler:
    handler: app/onPostEmote/handler.onPostEmote
    events:
      - websocket:
          route: onPostEmote
    vpc:
      securityGroupIds: ${self:custom.security-group-id.${sls:stage}}
      subnetIds: ${self:custom.vpc_subnet_id.${sls:stage}}
  defaultHandler:
    handler: app/sendEmotes/handler.sendEmotes
    events:
      - websocket:
          route: $default
    vpc:
      securityGroupIds: ${self:custom.security-group-id.${sls:stage}}
      subnetIds: ${self:custom.vpc_subnet_id.${sls:stage}}

resources:
  Conditions:
    IsOffline: !Equals ["${sls:stage}", "offline"]
  Resources:
    UserConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: user-connection-table-${sls:stage}
    EmoteReactionTable:
      Type: AWS::DynamoDB::Table
      Condition: IsOffline
      Properties:
        AttributeDefinitions:
          - AttributeName: emoteReactionId
            AttributeType: S
        KeySchema:
          - AttributeName: emoteReactionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: emote-reaction-table-${sls:stage}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Condition: IsOffline
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: users-table-${sls:stage}
    UserSubTable:
      Type: AWS::DynamoDB::Table
      Condition: IsOffline
      Properties:
        AttributeDefinitions:
          - AttributeName: userSub
            AttributeType: S
        KeySchema:
          - AttributeName: userSub
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: user-sub-table-${sls:stage}
    WebSocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: wordless-backend-websocket-${sls:stage}
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: $request.body.action

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  security-group-id:
    offline: ${env:VPC_SECURITY_GROUP_ID}
    dev: ${env:VPC_SECURITY_GROUP_ID}
    prod: ${env:VPC_SECURITY_GROUP_ID}
  vpc_subnet_id:
    offline: ${env:VPC_SUBNET_ID}
    dev: ${env:VPC_SUBNET_ID}
    prod: ${env:VPC_SUBNET_ID}
  db_host:
    offline: ${env:DB_HOST}
    dev: ${env:DB_HOST}
    prod: ${env:DB_HOST}
  db_user:
    offline: ${env:DB_USER}
    dev: ${env:DB_USER}
    prod: ${env:DB_USER}
  db_password:
    offline: ${env:DB_PASSWORD}
    dev: ${env:DB_PASSWORD}
    prod: ${env:DB_PASSWORD}
  db_name:
    offline: ${env:DB_NAME}
    dev: ${env:DB_NAME}
    prod: ${env:DB_NAME}
  cognito_user_pool_id:
    offline: ${env:COGNITO_USER_POOL_ID}
    dev: ${env:COGNITO_USER_POOL_ID}
    prod: ${env:COGNITO_USER_POOL_ID}
  websocket_endpoint:
    dev: ${env:WEBSOCKET_ENDPOINT}
    prod: ${env:WEBSOCKET_ENDPOINT}
  serverless-dynamodb:
    stages:
      - offline
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    
    seed:
      dev:
        sources:
          - table: user-connection-table-offline
            sources: [./seed/user-connection-table-offline.json]
          - table: emote-reaction-table-offline
            sources: [./seed/emote-reaction-table-offline.json]
          - table: user-sub-table-offline
            sources: [./seed/user-sub-table-offline.json]
          - table: users-table-offline
            sources: [./seed/users-table-offline.json]